### ISSUE TITLE
Support for getting logs from pods

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/kubernetes-fluent-client#214]
When using KFC within tests a common operation you might want to check are what logs a pod has - this could be done in pathbuilder by adding a value that adds `/log` to the end of the GET request - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#read-log-pod-v1-core - this could either be exposed as a `.Logs()` function that would assume / only work for pods or another filter-like thing that would tell a Get() to return logs.

**Comment by cmwylie19** [comment]
I'm going to go ahead and self-assign this one after leaving it open in the community channel for a few days. (if there are no objections)

Instead of changing the existing GET interface to also return a `.Log()` function from a pod, we could open it up to get logs from all things with podSelectors, like `sts/ds/svc/deploy/rs/job & cj(maybe)` also making it more  `kubectl` like, ie( `kubectl logs deploy/some-deploy -n some-ns`).

The way to do this is to [infer the kind](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go#L84C6-L84C24) of the [model](https://github.com/defenseunicorns/kubernetes-fluent-client/blob/b90ee90ea4413a34e761481f46bb1f75d9392d2e/src/fluent/index.ts#L24) , then get the logs from the pods that meet the podSelector. This would even allow us to get [allPods logs](https://github.com/kubernetes/kubernetes/pull/123874) even by default if the object has podLabels and include a prefix for each pod.

@Racer159 @jeff-mccoy What are your thoughts on this?
